#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 16:08:22 2019

@author: zdaruwala
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df4 = pd.read_csv('MyExpt_cells_MAN2A_TVP.txt', delimiter = '\t')

df4.columns = ['Image_number', 'Cell_number', 'PLA_count', 'Location_center_X', 'Location_center_Y', 'Location_center_Z', 'Cell_Number', 'Nuclei_Number']
print(df4.PLA_count.mean())
print(df4.PLA_count.std())
print(df4.PLA_count.max())
print(df4.PLA_count.median())

sns.boxplot(data=df4, x='PLA_count')

export_excel = df4.to_excel(r'/Users/zdaruwala/Documents/confocal images/06072019/cellprofiler data/MAN2A and TVP cell data.xlsx', index = None, header=True) 
